name: Build Stage
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  Build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v*.*.* ]]; then
            echo "Version: ${GITHUB_REF#refs/tags/v}"
            echo "VERSION=v${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "Version: latest"
            echo "VERSION=latest" >> $GITHUB_ENV
          fi
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v3
      - name: Setup Golang
        id: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"
      - name: Download Module
        id: download
        run: go mod download
      - name: Build
        id: build
        run: go build -o ./bin/main ./cmd/main.go
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/go-rest-api:${{ env.VERSION }}
