name: Unit Testing Stage
on:
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: unit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"
      - name: Download Module
        run: go mod download
      - name: Run unit-testing
        run: go test ./internal/repository -v
